services:
    _defaults:
        autowire: true
        autoconfigure: true

    Symfony\Component\Console\Application:
        public: true

    Symfony\Component\Filesystem\Filesystem:
        public: true

    MykytaPopov\VPatch\Command\GenerateCommand:
        public: true

    MykytaPopov\VPatch\FinderInterface:
        class: MykytaPopov\VPatch\Finder

    MykytaPopov\VPatch\DifferInterface:
        class: MykytaPopov\VPatch\Differ

    MykytaPopov\VPatch\PathResolverInterface:
        class: MykytaPopov\VPatch\PathResolver
